export const quotas = {
  free: {
    title: '免费版',
    app: 3,
    package: 30,
    packageSize: '30m',
    bundle: 30,
    bundleSize: '3m',
    pv: 1000,
  },
  standard: {
    title: '标准版',
    app: 5,
    package: 50,
    packageSize: '150m',
    bundle: 50,
    bundleSize: '15m',
    pv: 10000,
  },
  premium: {
    title: '高级版',
    app: 10,
    package: 60,
    packageSize: '500m',
    bundle: 60,
    bundleSize: '50m',
    pv: 100000,
  },
  pro: {
    title: '专业版',
    app: 50,
    package: 100,
    packageSize: '2000m',
    bundle: 100,
    bundleSize: '200m',
    pv: 1000000,
  },
  vip1: {
    title: '大客户VIP1',
    app: 50,
    package: 100,
    packageSize: '2000m',
    bundle: 100,
    bundleSize: '200m',
    pv: 10000000,
  },
  vip2: {
    title: '大客户VIP2',
    app: 50,
    package: 100,
    packageSize: '2000m',
    bundle: 100,
    bundleSize: '200m',
    pv: 50000000,
  },
  vip3: {
    title: '大客户VIP3',
    app: 50,
    package: 100,
    packageSize: '2000m',
    bundle: 100,
    bundleSize: '200m',
    pv: 100000000,
  },
} as const;

export const products = {
  free: {
    price: 0,
    title: 'Pushy 热更新服务免费版',
    summary: 'Pushy 热更新服务免费版',
  },
  standard: {
    price: 960,
    title: 'Pushy 热更新服务标准版',
    summary: 'Pushy 热更新服务标准版一年期服务',
  },
  premium: {
    price: 2400,
    title: 'Pushy 热更新服务高级版',
    summary: 'Pushy 热更新服务高级版一年期服务',
  },
  pro: {
    price: 7200,
    title: 'Pushy 热更新服务专业版',
    summary: 'Pushy 热更新服务专业版一年期服务',
  },
  vip1: {
    price: 30_000,
    title: 'Pushy 热更新服务大客户 VIP1',
    summary: 'Pushy 热更新服务大客户 VIP1 一年期服务',
  },
  vip2: {
    price: 60_000,
    title: 'Pushy 热更新服务大客户 VIP2',
    summary: 'Pushy 热更新服务大客户 VIP2 一年期服务',
  },
  vip3: {
    price: 120_000,
    title: 'Pushy 热更新服务大客户 VIP3',
    summary: 'Pushy 热更新服务大客户 VIP3 一年期服务',
  },
  custom: {
    price: 0,
    title: 'Pushy 热更新服务定制版',
    summary: 'Pushy 热更新服务定制版一年期服务',
  },
} as const;
